version: 0.2

env:
    variables:
        TASK_DEFINITION_REVISION: "1"
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo Build started on `date`
            - echo Building the prestashop Docker image...
            - docker build -f Dockerfile -t $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION  .
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:latest
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:latest
            - printf '[{"name":"prestashop","imageUri":"%s"}]' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM:$CODEBUILD_RESOLVED_SOURCE_VERSION"> imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json
