version: 0.2

env:
    variables:
        TASK_DEFINITION_REVISION: "1"
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_PHP_FPM
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -f Dockerfile -t $IMAGE_REPO_NAME_PHP_FPM:$COMMIT_HASH  .
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$COMMIT_HASH $REPOSITORY_URI:$COMMIT_HASH
            - docker tag $IMAGE_REPO_NAME_PHP_FPM:$COMMIT_HASH $REPOSITORY_URI:latest
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:$COMMIT_HASH
            - docker push $REPOSITORY_URI:latest
            - printf '[{"name":"prestashop","imageUri":"%s"}]' "$REPOSITORY_URI:$COMMIT_HASH"> imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json
