version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_PASSWORD=my_password
      - PRESTASHOP_LANGUAGE=pl
      - PRESTASHOP_COUNTRY=pl
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
      - ./my_module:/bitnami/prestashop/modules/my_module
      #- ./my_theme:/bitnami/prestashop/my_theme
      #- ./override:/bitnami/prestashop/override
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
